### ISSUE TITLE
大佬arm设备可以运行吗？

### ISSUE THREAD

**Issue by yhxxm** [ssili126/tv#67]
linux系统 我安装了arm版chomium 执行不了 是不支持还是我的方法没对 可以解决吗？amd设备一切正常

**Comment by ssili126** [comment]
这个没有试过

**Comment by yhxxm** [comment]
root@3a07b9cc8c4d:/home/hipy-sniffer/iptv# python3 itvall.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/driver_finder.py", line 67, in _binary_paths
    output = SeleniumManager().binary_paths(self._to_args())
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/selenium_manager.py", line 45, in binary_paths
    args = [str(self._get_binary())] + args
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/selenium_manager.py", line 83, in _get_binary
    raise WebDriverException(f"Unsupported platform/architecture combination: {sys.platform}/{arch}")
selenium.common.exceptions.WebDriverException: Message: Unsupported platform/architecture combination: linux/aarch64


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "itvall.py", line 87, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 50, in __init__
    if finder.get_browser_path():
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
  File "/usr/local/lib/python3.8/site-packages/selenium/webdriver/common/driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by yhxxm** [comment]
执行完就这样了 看来arm设备运行不起来
